import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PublicSiteHeader } from "@/components/public-site-header";
import { isPublicLocale } from "@/data/academy/catalog";
import { metadataBaseFor } from "@/data/site-metadata";
import { getAppConfig } from "@/lib/app/config";
import { createPractitionerRepository } from "@/lib/practitioners/repository";
import type { PublicPractitioner } from "@/lib/practitioners/public-types";

type PageProps={params:Promise<{locale:string;slug:string}>};
export const dynamic="force-dynamic";export const revalidate=0;
async function load(locale:string,slug:string):Promise<PublicPractitioner|null>{try{return await createPractitionerRepository(getAppConfig()).getPublicPractitioner(slug,locale) as PublicPractitioner}catch{return null}}
export async function generateMetadata({params}:PageProps):Promise<Metadata>{const{locale,slug}=await params;if(!isPublicLocale(locale))return{title:"Not found"};const p=await load(locale,slug);if(!p)return{title:"Not found",robots:{index:false,follow:false}};const name=p.profile.displayName||p.profile.name||(locale==="es"?"Profesional":"Practitioner");return{metadataBase:metadataBaseFor(),title:`${name} | Holistic House`,description:p.profile.shortBio||"",alternates:{canonical:`/${locale}/masters/${slug}`}}}
export default async function MasterProfile({params}:PageProps){const{locale,slug}=await params;if(!isPublicLocale(locale))notFound();const p=await load(locale,slug);if(!p)notFound();const ru=locale==="ru",es=locale==="es",profile=p.profile||{},name=profile.displayName||profile.name||"Practitioner";return <main className="services-shell services-shell--studio" lang={locale}><PublicSiteHeader locale={locale}/>
 <section className="services-studio-hero"><div className="services-studio-hero-copy"><p className="homeopathy-kicker">{ru?"Практик Holistic House":es?"Profesional de Holistic House":"Holistic House practitioner"}</p><h1>{name}</h1><p>{profile.professionalTitle}</p><p>{profile.shortBio}</p><p>{[profile.city,profile.region,profile.country].filter(Boolean).join(", ")}</p><div className="hh-actions">{p.isPartner&&<span className="hh-badge">{es?"Colaborador de Holistic House":"Holistic House Partner"}</span>}{p.credentials.some((x)=>x.verificationStatus==="verified")&&<span className="hh-badge">{ru?"Credentials проверены":es?"Credenciales verificadas":"Credentials verified"}</span>}</div></div></section>
 {es&&<p className="remedy-disclaimer">Las biografías aportadas por cada profesional pueden aparecer en su idioma original.</p>}
 <section className="services-studio-approach"><div><p className="homeopathy-kicker">{ru?"Подход":es?"Enfoque":"Approach"}</p><h2>{ru?"О практике":es?"Sobre el profesional":"About"}</h2></div><div><p>{profile.fullBio||profile.shortBio}</p>{profile.methods?.length?<p><strong>{ru?"Методы: ":es?"Métodos: ":"Methods: "}</strong>{profile.methods.join(" · ")}</p>:null}{profile.languages?.length?<p><strong>{ru?"Языки: ":es?"Idiomas: ":"Languages: "}</strong>{profile.languages.join(" · ").toUpperCase()}</p>:null}</div></section>
 {p.credentials.length>0&&<section className="services-method-videos"><div className="services-method-videos-heading"><p className="homeopathy-kicker">{ru?"Квалификации":es?"Formación":"Credentials"}</p><h2>{ru?"Заявленные квалификации":es?"Formación declarada":"Professional background"}</h2></div><div className="services-studio-grid services-studio-grid--three">{p.credentials.map((x)=><article className="services-studio-card" key={x.id}><h3>{x.title}</h3><p>{[x.issuer,x.jurisdiction,x.reference].filter(Boolean).join(" · ")}</p><p className="remedy-disclaimer">{x.verificationStatus==="verified"?(ru?"Проверено Holistic House":es?"Verificado por Holistic House":"Credentials verified"):(ru?"Заявлено практиком":es?"Declarado por el profesional":"Declared by practitioner")}</p></article>)}</div></section>}
 <section className="services-method-videos"><div className="services-method-videos-heading"><p className="homeopathy-kicker">{ru?"Услуги":es?"Servicios":"Services"}</p><h2>{ru?"Доступные форматы":es?"Sesiones disponibles":"Available offerings"}</h2></div><div className="services-studio-grid services-studio-grid--three">{[...p.services].sort((a,b)=>Number(b.pricingMode!=="contact"&&b.confirmedPrice===0)-Number(a.pricingMode!=="contact"&&a.confirmedPrice===0)).map((s)=>{const free=s.pricingMode!=="contact"&&s.confirmedPrice===0;return <article className="services-studio-card services-studio-card--detailed" key={s.id}>{free?<p className="services-marketplace-free-badge">{ru?"Бесплатно":es?"Gratis":"Free"}</p>:null}<h3>{s.copy.title}</h3><p>{s.copy.shortDescription}</p><Link href={`/${locale}/services/${p.slug}/${s.slug}`}>{free?(ru?"Пройти бесплатно":es?"Solicitar gratis":"Start free"):(ru?"Открыть услугу":es?"Ver servicio":"View service")}<span aria-hidden="true">→</span></Link></article>})}</div></section>
 </main>}
