import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PublicSiteHeader } from "@/components/public-site-header";
import { isSupportedLocale } from "@/data/remedies";
import { metadataBaseFor } from "@/data/site-metadata";
import { getAppConfig } from "@/lib/app/config";
import { createPractitionerRepository } from "@/lib/practitioners/repository";
import type { PublicPractitioner } from "@/lib/practitioners/public-types";

type PageProps={params:Promise<{locale:string;slug:string}>};
export const dynamic="force-dynamic";export const revalidate=0;
async function load(locale:string,slug:string):Promise<PublicPractitioner|null>{try{return await createPractitionerRepository(getAppConfig()).getPublicPractitioner(slug,locale) as PublicPractitioner}catch{return null}}
export async function generateMetadata({params}:PageProps):Promise<Metadata>{const{locale,slug}=await params;if(!isSupportedLocale(locale))return{title:"Not found"};const p=await load(locale,slug);if(!p)return{title:"Not found",robots:{index:false,follow:false}};const name=p.profile.displayName||p.profile.name||"Practitioner";return{metadataBase:metadataBaseFor(),title:`${name} | Holistic House`,description:p.profile.shortBio||"",alternates:{canonical:`/${locale}/masters/${slug}`}}}
export default async function MasterProfile({params}:PageProps){const{locale,slug}=await params;if(!isSupportedLocale(locale))notFound();const p=await load(locale,slug);if(!p)notFound();const ru=locale==="ru",profile=p.profile||{},name=profile.displayName||profile.name||"Practitioner";return <main className="services-shell services-shell--studio" lang={locale}><PublicSiteHeader locale={locale}/>
 <section className="services-studio-hero"><div className="services-studio-hero-copy"><p className="homeopathy-kicker">{ru?"Практик Holistic House":"Holistic House practitioner"}</p><h1>{name}</h1><p>{profile.professionalTitle}</p><p>{profile.shortBio}</p><p>{[profile.city,profile.region,profile.country].filter(Boolean).join(", ")}</p><div className="hh-actions">{p.isPartner&&<span className="hh-badge">Holistic House Partner</span>}{p.credentials.some((x)=>x.verificationStatus==="verified")&&<span className="hh-badge">{ru?"Credentials проверены":"Credentials verified"}</span>}</div></div></section>
 <section className="services-studio-approach"><div><p className="homeopathy-kicker">{ru?"Подход":"Approach"}</p><h2>{ru?"О практике":"About"}</h2></div><div><p>{profile.fullBio||profile.shortBio}</p>{profile.methods?.length?<p><strong>{ru?"Методы: ":"Methods: "}</strong>{profile.methods.join(" · ")}</p>:null}{profile.languages?.length?<p><strong>{ru?"Языки: ":"Languages: "}</strong>{profile.languages.join(" · ").toUpperCase()}</p>:null}</div></section>
 {p.credentials.length>0&&<section className="services-method-videos"><div className="services-method-videos-heading"><p className="homeopathy-kicker">{ru?"Квалификации":"Credentials"}</p><h2>{ru?"Заявленные квалификации":"Professional background"}</h2></div><div className="services-studio-grid services-studio-grid--three">{p.credentials.map((x)=><article className="services-studio-card" key={x.id}><h3>{x.title}</h3><p>{[x.issuer,x.jurisdiction,x.reference].filter(Boolean).join(" · ")}</p><p className="remedy-disclaimer">{x.verificationStatus==="verified"?(ru?"Проверено Holistic House":"Credentials verified"):(ru?"Заявлено практиком":"Declared by practitioner")}</p></article>)}</div></section>}
 <section className="services-method-videos"><div className="services-method-videos-heading"><p className="homeopathy-kicker">{ru?"Услуги":"Services"}</p><h2>{ru?"Доступные форматы":"Available offerings"}</h2></div><div className="services-studio-grid services-studio-grid--three">{p.services.map((s)=><article className="services-studio-card services-studio-card--detailed" key={s.id}><h3>{s.copy.title}</h3><p>{s.copy.shortDescription}</p><Link href={`/${locale}/services/${p.slug}/${s.slug}`}>{ru?"Открыть услугу":"View service"}<span aria-hidden="true">→</span></Link></article>)}</div></section>
 </main>}
