import Image from 'next/image';
import Link from 'next/link';
import { BriefcaseBusiness, Flower2, Sparkles } from 'lucide-react';
import { PublicSiteHeader } from '@/components/public-site-header';
import { spanishMetadata } from '@/lib/spanish-metadata';
export const metadata = spanishMetadata('/es/services', 'Servicios — Holistic House', 'Constelaciones empresariales, Alquimia del Alma, psicohomeopatía y constelaciones arquetípicas.');
const cards = [
  { id: 'business', icon: BriefcaseBusiness, title: 'Constelaciones empresariales', subtitle: 'Explorar las perspectivas de los proyectos empresariales', text: 'Exploración sistémica de un proyecto: sus perspectivas, dinámicas ocultas, asociaciones, roles, dinero, limitaciones y posibles próximos pasos. El objetivo es ampliar la mirada y explorar las decisiones mediante el trabajo de constelaciones.' },
  { id: 'alchemy', icon: Flower2, title: 'Alquimia del Alma / Psicohomeopatía', subtitle: 'Trabajo individual con estados interiores', text: 'Formato desarrollado por el autor que combina el trabajo con imágenes y la exploración sistémica con orientación sobre recursos de apoyo. Se centra en los estados interiores, los patrones recurrentes, los recursos y el movimiento hacia una mayor integración.' },
  { id: 'archetypal', icon: Sparkles, title: 'Constelaciones arquetípicas', subtitle: 'Misterios e iniciaciones', text: 'Trabajo vivencial con arquetipos, imágenes mitológicas, estructuras rituales y el campo transpersonal, de forma individual o en grupo.' },
];
export default function SpanishServicesPage() {
  return <main className="services-shell services-shell--studio" lang="es"><PublicSiteHeader locale="es" />
    <section className="services-studio-hero"><div className="services-studio-hero-copy"><p className="homeopathy-kicker">Tres direcciones de trabajo</p><h1>Servicios</h1><p>Tres formatos para distintas necesidades: negocios y decisiones, estados interiores y desarrollo, y exploración arquetípica y transpersonal.</p><Link className="services-studio-primary" href="#consultation">Empieza con una breve conversación<span aria-hidden="true">→</span></Link></div><div className="services-studio-photo" aria-hidden="true"><Image src="/images/holistic-house/hero-olive-incense.webp" alt="" fill priority sizes="(max-width: 767px) 100vw, 44vw" /></div></section>
    <section className="services-studio-grid services-studio-grid--three" aria-label="Servicios">{cards.map(({ id, icon: Icon, title, subtitle, text }) => <article className="services-studio-card services-studio-card--detailed" id={id} key={id}><span className="services-studio-icon" aria-hidden="true"><Icon /></span><h2>{title}</h2><p className="services-studio-card-subtitle">{subtitle}</p><p>{text}</p></article>)}</section>
    <section className="services-studio-approach"><div><p className="homeopathy-kicker">Sobre el enfoque</p><h2>Una práctica, tres direcciones</h2></div><div><p>En los tres formatos trabajo con el campo sistémico, las imágenes y una atención cercana a las dinámicas. Lo que cambia es el foco: los negocios, los estados interiores o el nivel arquetípico.</p><Link href="/es/about">Sobre mí<span aria-hidden="true">→</span></Link></div></section>
    <section className="services-consultation services-consultation--studio" id="consultation"><div><p className="homeopathy-kicker">Primer paso</p><h2>Empieza con una breve conversación</h2><p>Cuéntame qué te gustaría explorar y elegiremos cuál de los tres formatos encaja mejor en este momento.</p></div><div><a href="https://t.me/AndyTherapist" rel="noreferrer" target="_blank">Escribir por Telegram</a><a href="https://wa.me/14376066502" rel="noreferrer" target="_blank">WhatsApp</a><Link href="/es/about#personal-consultation-title">Solicitar una consulta personal</Link></div></section>
    <p className="remedy-disclaimer services-disclaimer">Las constelaciones empresariales son un método de exploración sistémica y no sustituyen el análisis financiero ni las previsiones profesionales. Los materiales de psicohomeopatía tienen una finalidad educativa y no sustituyen el diagnóstico ni el tratamiento médico.</p>
  </main>;
}
