export const COPY = {
  en: {
    portrait: 'My profile',
    monitoring: 'Psi-Monitoring',
    tests: 'My tests',
    history: 'History',
    reports: 'Reports from Andy',
    consultations: 'Consultations',
    settings: 'Account & privacy',
    signout: 'Sign out',
    loading: 'Opening your space…',
    retry: 'Try again',
    signin: 'Continue with Google',
    welcome: 'A little space to understand yourself.',
    intro: 'Notice how you feel, discover your personal tendencies and see what changes over time.',
    private: 'Private by default. You choose what to share.',
    unavailable: 'The new personal app is not connected yet.',
    unavailableText:
      'Registration and saving require the dedicated app database and Google sign-in configuration. Your existing private cabinet is still available.',
    legacy: 'Open existing private cabinet',
    back: 'Back',
    next: 'Next',
    saveExit: 'Save and exit',
    saving: 'Saving…',
    saved: 'Saved securely',
    unsaved: 'Not saved yet',
    saveError: 'Not saved. Keep this page open and retry.',
    conflict: 'This record changed in another tab. Reload the saved version before continuing.',
    reload: 'Reload saved version',
    start: 'Start',
    resume: 'Continue',
    view: 'View result',
    viewTrend: 'View trend',
    repeat: 'Take again',
    cancel: 'Cancel',
    close: 'Close',
    finish: 'Save my result',
    state: 'How I feel now',
    weekly: 'Weekly Psychic Health',
    symptoms: 'Symptoms',
    functioning: 'Function',
    resources: 'Resources',
    personality: 'Personality tendencies',
    nextStep: 'Next step',
    nextStateTitle: 'Check how you feel now',
    nextStateText: 'A short Current State check-in gives your portrait its first factual reference point.',
    nextTendenciesTitle: 'Add your personality tendencies',
    nextTendenciesText: 'This separate, optional layer describes general tendencies rather than today’s state.',
    nextHistoryTitle: 'View changes over time',
    nextHistoryText: 'Compare compatible, dated check-ins without turning them into a diagnosis or a trend claim.',
    nextReportTitle: 'Open your latest report',
    nextReportText: 'This is material explicitly shared with you by Andy.',
    nextConsultationTitle: 'View your consultation request',
    nextConsultationText: 'See the current request status or choose what to do next.',
    nextCheckinTitle: 'Add a new check-in when useful',
    nextCheckinText: 'Your suggested repeat window has arrived. This is optional, not a daily obligation.',
    addTendencies: 'Add tendencies',
    viewHistory: 'View History',
    viewConsultations: 'View consultations',
    openReport: 'Open report',
    guideTitle: 'What will appear here',
    guideState: 'how things feel right now.',
    guideTendencies: 'a separate background layer.',
    guideHistory: 'factual changes across dated check-ins.',
    guideReports: 'practitioner-authored material you choose to save.',
    empty: 'Your portrait starts with one small check-in.',
    emptyText:
      'Five questions about right now. Your first result becomes a reference point, not a diagnosis.',
    stateDescription:
      'Resource, inner tension, fatigue and the impact of your current difficulty. Five scales and optional context.',
    weeklyDescription:
      'Eight original Holistic House self-monitoring scales for the past 7 days: state, load, recovery, clarity, connection and functioning.',
    traitDescription:
      'An optional 20-item self-report about how you generally see yourself. English original, Mini-IPIP.',
    traitNotice:
      'This questionnaire is in English. Use it only if you are comfortable with the original wording. It is not an IQ test, a diagnosis or a complete description of you.',
    general: 'Describe how you generally see yourself, not only how you feel today.',
    pastWeek: 'Answer about the past 7 days. This is self-monitoring, not a diagnostic scale.',
    rightNow: 'Answer for right now. There is no right or wrong answer.',
    baseline: 'First measurement',
    latest: 'Latest measurement',
    previous: 'Previous measurement',
    noChange: 'A second compatible check-in will make comparison possible.',
    noResults: 'No completed results yet.',
    measured: 'Measured',
    source: 'Source',
    oldMeasure: 'Not remeasured in this check-in',
    scale: 'Scale',
    points: 'points',
    details: 'Explanation & history',
    optional: 'Optional context',
    contextAtCheckIn: 'Context at this check-in',
    focus: 'What is on your mind?',
    trigger: 'What changed or seems to trigger this?',
    helps: 'What helps you?',
    desiredChange: 'What would you like to change?',
    note: 'Anything else you want to note?',
    skip: 'You may leave these fields blank.',
    decline: 'Discard this unfinished test',
    nonDiagnostic:
      'Self-observation, not medical diagnosis. This space is not monitored for emergencies.',
    patterns: 'Patterns are not inferred automatically from a few scores.',
    compare: 'Compare measurements',
    from: 'From',
    to: 'To',
    dimension: 'Dimension',
    date: 'Date',
    value: 'Value',
    change: 'Difference',
    versionBoundary: 'Only compatible wording, scales and versions are compared.',
    historyIntro: 'Your dated check-ins, life events and saved reports stay in one factual timeline.',
    since: 'Since',
    context: 'Life events & notes',
    addEvent: 'Add a note about what changed',
    editJournal: 'Edit note',
    label: 'What changed around this time?',
    save: 'Save',
    delete: 'Delete',
    contextNote: 'Events give context. Their timing does not establish a cause.',
    reportsIntro: 'Reports are practitioner-authored material that you explicitly chose to save here.',
    reportsEmpty: 'No reports from Andy have been saved yet.',
    reportsEmptyText: 'When a report is shared with you and you choose to save it, it will appear here without opening the rest of a legacy Cabinet.',
    reportFromAndy: 'Report from Andy',
    request: 'Request a consultation',
    requests: 'My requests',
    price: 'Price confirmed before booking',
    requestNote:
      'A request is not a confirmed appointment. Andy will contact you separately to discuss details.',
    consultationsIntro: 'Choose a consultation when it feels useful. Requests stay separate from booking and from any private result you have not chosen to share.',
    contact: 'How should Andy contact you?',
    message: 'Your message (optional)',
    share: 'Share one result summary (optional)',
    shareNone: 'Do not share a result',
    shareConfirm: 'I agree to send exactly the summary shown below to Andy.',
    submitRequest: 'Send request',
    requestReceived: 'Request received',
    requested: 'Received',
    contacted: 'Contacted',
    closed: 'Closed',
    cancelled: 'Cancelled',
    withdraw: 'Cancel request',
    unshare: 'Remove shared summary',
    sharingNote:
      'No raw answers or future results are shared. Removing access cannot recall information already read.',
    name: 'Name',
    timezone: 'Time zone',
    goal: 'Your current interest',
    explore: 'Self-exploration',
    body: 'Body & emotional context',
    relationships: 'Relationships',
    resource: 'Resource & recovery',
    business: 'Work, business or a situation',
    adult: 'I am 18 or older.',
    necessary:
      'I agree to private processing of my answers and results for this self-observation app.',
    marketing: 'I agree to optional marketing contact. This is not required.',
    continue: 'Create my private space',
    privacy:
      'Your answers stay in your account. A practitioner receives only a consultation request and the summary you explicitly choose to send.',
    export: 'Export my app data',
    deletion: 'Request deletion',
    deletionNote:
      'This disables your app account and records a deletion request. Legacy consultation records are separate. Do not use this action merely to sign out.',
    deletionConfirm: 'Type DELETE to request deletion of your self-service app data.',
    deletionReceived:
      'Deletion requested. App access is disabled. This does not claim that provider backups or legacy records have already been erased.',
    reauth: 'For this action, sign out and sign in again, then return here within ten minutes.',
    allDevices: 'Sign out on all devices',
    account: 'Account',
    result: 'Result',
    notFound: 'This record is not available in your account.',
    error: 'Something could not be saved or loaded. Please retry.',
    dateWarning: 'Choose two different compatible measurements.',
    emptyRequests: 'No consultation requests yet.',
    emptyServices: 'No published services are available right now.',
    continueLater: 'You can return whenever it is useful. There is no daily testing obligation.',
  },
  ru: {
    portrait: 'Мой профиль',
    monitoring: 'Пси-мониторинг',
    tests: 'Мои тесты',
    history: 'История',
    reports: 'Отчёты от Andy',
    consultations: 'Консультации',
    settings: 'Аккаунт и приватность',
    signout: 'Выйти',
    loading: 'Открываем ваше пространство…',
    retry: 'Повторить',
    signin: 'Продолжить с Google',
    welcome: 'Пространство, чтобы лучше понять себя.',
    intro:
      'Замечайте своё состояние, исследуйте личностные особенности и наблюдайте изменения во времени.',
    private: 'По умолчанию всё приватно. Вы выбираете, чем делиться.',
    unavailable: 'Новое приложение пока не подключено.',
    unavailableText:
      'Для регистрации и сохранения нужна отдельная база приложения и настройка входа через Google. Прежний приватный кабинет доступен.',
    legacy: 'Открыть прежний приватный кабинет',
    back: 'Назад',
    next: 'Далее',
    saveExit: 'Сохранить и выйти',
    saving: 'Сохраняем…',
    saved: 'Сохранено',
    unsaved: 'Ещё не сохранено',
    saveError: 'Не сохранено. Не закрывайте страницу и повторите попытку.',
    conflict:
      'Запись изменилась в другой вкладке. Загрузите сохранённую версию, прежде чем продолжить.',
    reload: 'Загрузить сохранённую версию',
    start: 'Начать',
    resume: 'Продолжить',
    view: 'Открыть результат',
    viewTrend: 'Динамика',
    repeat: 'Пройти снова',
    cancel: 'Отмена',
    close: 'Закрыть',
    finish: 'Сохранить результат',
    state: 'Моё состояние сейчас',
    weekly: 'Психическое состояние за неделю',
    symptoms: 'Симптомы',
    functioning: 'Функционирование',
    resources: 'Ресурсы',
    personality: 'Личностные особенности',
    nextStep: 'Следующий шаг',
    nextStateTitle: 'Отметить ваше состояние сейчас',
    nextStateText: 'Короткий check-in Current State создаст первую фактическую точку для вашего портрета.',
    nextTendenciesTitle: 'Добавить личностные особенности',
    nextTendenciesText: 'Это отдельный необязательный слой о привычных особенностях, а не о состоянии сегодня.',
    nextHistoryTitle: 'Посмотреть изменения со временем',
    nextHistoryText: 'Сравнивайте совместимые замеры с датами без диагноза и без заявлений о тренде.',
    nextReportTitle: 'Открыть последний отчёт',
    nextReportText: 'Это материал, которым Andy явно поделился с вами.',
    nextConsultationTitle: 'Посмотреть заявку на консультацию',
    nextConsultationText: 'Проверьте статус заявки или выберите следующий шаг.',
    nextCheckinTitle: 'Добавить новый check-in, когда это полезно',
    nextCheckinText: 'Наступил предложенный срок повторения. Это необязательно и не является ежедневной задачей.',
    addTendencies: 'Добавить особенности',
    viewHistory: 'Открыть историю',
    viewConsultations: 'Открыть консультации',
    openReport: 'Открыть отчёт',
    guideTitle: 'Что появится здесь',
    guideState: 'как вы чувствуете себя сейчас.',
    guideTendencies: 'отдельный фоновый слой.',
    guideHistory: 'фактические изменения в check-in с датами.',
    guideReports: 'материалы от специалиста, которые вы решили сохранить.',
    empty: 'Ваш портрет начинается с короткого наблюдения.',
    emptyText:
      'Пять вопросов о состоянии сейчас. Первый результат станет точкой сравнения, а не диагнозом.',
    stateDescription:
      'Ресурс, напряжение, усталость и влияние текущей трудности. Пять шкал и необязательный комментарий.',
    weeklyDescription:
      'Восемь оригинальных шкал Holistic House за последние 7 дней: состояние, нагрузка, восстановление, ясность, связь и функционирование.',
    traitDescription:
      'Необязательный опрос из 20 утверждений о том, как вы обычно себя описываете. Английский оригинал Mini-IPIP.',
    traitNotice:
      'Этот опрос — на английском. Проходите его, только если вам понятны исходные формулировки. Это не тест IQ, не диагноз и не полное описание личности.',
    general: 'Описывайте себя в целом, а не только сегодняшнее состояние.',
    pastWeek: 'Отвечайте о последних 7 днях. Это самонаблюдение, а не диагностическая шкала.',
    rightNow: 'Отвечайте о состоянии сейчас. Здесь нет правильных или неправильных ответов.',
    baseline: 'Первый замер',
    latest: 'Последний замер',
    previous: 'Предыдущий замер',
    noChange: 'После второго сопоставимого замера можно будет увидеть разницу.',
    noResults: 'Завершённых результатов пока нет.',
    measured: 'Дата замера',
    source: 'Источник',
    oldMeasure: 'Не измерялось повторно в этом тесте',
    scale: 'Шкала',
    points: 'баллов',
    details: 'Описание и история',
    optional: 'Контекст — по желанию',
    contextAtCheckIn: 'Контекст на момент этого check-in',
    focus: 'Что сейчас занимает ваше внимание?',
    trigger: 'Что изменилось или что, кажется, запускает это?',
    helps: 'Что помогает вам?',
    desiredChange: 'Что вы хотели бы изменить?',
    note: 'Что ещё важно отметить?',
    skip: 'Эти поля можно оставить пустыми.',
    decline: 'Удалить незавершённый тест',
    nonDiagnostic:
      'Самонаблюдение, а не медицинская диагностика. Это пространство не отслеживается как канал экстренной помощи.',
    patterns: 'По нескольким баллам система не приписывает вам устойчивые паттерны.',
    compare: 'Сравнить замеры',
    from: 'От',
    to: 'До',
    dimension: 'Показатель',
    date: 'Дата',
    value: 'Значение',
    change: 'Разница',
    versionBoundary: 'Сравниваются только совместимые формулировки, шкалы и версии.',
    historyIntro: 'Check-in с датами, жизненные события и сохранённые отчёты собраны в одну фактическую историю.',
    since: 'С',
    context: 'Жизненные события и заметки',
    addEvent: 'Добавить заметку об изменении',
    editJournal: 'Изменить заметку',
    label: 'Что изменилось в это время?',
    save: 'Сохранить',
    delete: 'Удалить',
    contextNote: 'События добавляют контекст. Совпадение по времени не доказывает причину.',
    reportsIntro: 'Это материалы от специалиста, которые вы явно решили сохранить здесь.',
    reportsEmpty: 'Сохранённых отчётов от Andy пока нет.',
    reportsEmptyText: 'Когда Andy поделится отчётом и вы решите сохранить его, он появится здесь без открытия остального прежнего Кабинета.',
    reportFromAndy: 'Отчёт от Andy',
    request: 'Запросить консультацию',
    requests: 'Мои заявки',
    price: 'Стоимость согласуется до записи',
    requestNote:
      'Заявка не означает подтверждённую запись. Практик свяжется с вами отдельно и обсудит детали.',
    consultationsIntro: 'Выберите услугу, когда это будет полезно. Заявка существует отдельно от записи и от результатов, которыми вы не решили делиться.',
    contact: 'Как практик может с вами связаться?',
    message: 'Ваше сообщение — по желанию',
    share: 'Передать краткий результат — по желанию',
    shareNone: 'Не передавать результат',
    shareConfirm: 'Я согласен передать этому практику именно то резюме, которое показано ниже.',
    submitRequest: 'Отправить заявку',
    requestReceived: 'Заявка получена',
    requested: 'Получена',
    contacted: 'Связались',
    closed: 'Закрыта',
    cancelled: 'Отменена',
    withdraw: 'Отменить заявку',
    unshare: 'Закрыть доступ к резюме',
    sharingNote:
      'Исходные ответы и будущие результаты не передаются. Закрытие доступа не может отозвать уже прочитанную информацию.',
    name: 'Имя',
    timezone: 'Часовой пояс',
    goal: 'Что вам сейчас интересно',
    explore: 'Исследовать себя',
    body: 'Тело и эмоциональный контекст',
    relationships: 'Отношения',
    resource: 'Ресурс и восстановление',
    business: 'Работа, бизнес или ситуация',
    adult: 'Мне 18 лет или больше.',
    necessary:
      'Я согласен на приватную обработку ответов и результатов для работы приложения самонаблюдения.',
    marketing:
      'Я согласен получать необязательные информационные предложения. Это не условие доступа.',
    continue: 'Создать личное пространство',
    privacy:
      'Ответы хранятся в вашем аккаунте. Специалист получает только заявку и то краткое резюме, которое вы явно разрешили передать.',
    export: 'Выгрузить мои данные',
    deletion: 'Запросить удаление',
    deletionNote:
      'Доступ к приложению будет отключён, а запрос удаления сохранён. Прежние документы консультаций существуют отдельно. Для обычного выхода эта кнопка не нужна.',
    deletionConfirm: 'Введите DELETE, чтобы запросить удаление данных приложения.',
    deletionReceived:
      'Удаление запрошено. Доступ к приложению отключён. Это не означает, что резервные копии провайдера или прежние документы уже удалены.',
    reauth:
      'Для этого действия выйдите и войдите снова, затем вернитесь сюда в течение десяти минут.',
    allDevices: 'Выйти на всех устройствах',
    account: 'Аккаунт',
    result: 'Результат',
    notFound: 'Эта запись недоступна в вашем аккаунте.',
    error: 'Не удалось сохранить или загрузить данные. Повторите попытку.',
    dateWarning: 'Выберите два разных совместимых замера.',
    emptyRequests: 'Заявок на консультацию пока нет.',
    emptyServices: 'Сейчас нет опубликованных услуг.',
    continueLater: 'Возвращайтесь, когда это полезно. Ежедневное прохождение не требуется.',
  },
}
const LABELS = {
  'state.problem_intensity': ['Difficulty', 'Трудность'],
  'state.resource': ['Resource', 'Ресурс'],
  'state.tension': ['Inner tension', 'Напряжение'],
  'state.fatigue': ['Fatigue', 'Усталость'],
  'state.life_impact': ['Impact on daily life', 'Влияние на жизнь'],
  'weekly.mood': ['Emotional state', 'Эмоциональное состояние'],
  'weekly.tension': ['Anxiety / tension', 'Тревога / напряжение'],
  'weekly.load': ['Stress / load', 'Стресс / нагрузка'],
  'weekly.recovery': ['Sleep / recovery', 'Сон / восстановление'],
  'weekly.energy': ['Energy', 'Энергия'],
  'weekly.clarity': ['Mental clarity', 'Ясность мышления'],
  'weekly.connection': ['Connection / support', 'Связь / поддержка'],
  'weekly.functioning': ['Daily functioning', 'Повседневное функционирование'],
  'trait.extraversion': ['Extraversion', 'Экстраверсия'],
  'trait.agreeableness': ['Agreeableness', 'Доброжелательность'],
  'trait.conscientiousness': ['Conscientiousness', 'Добросовестность'],
  'trait.neuroticism': [
    'Emotional reactivity (Neuroticism)',
    'Эмоциональная реактивность (Neuroticism)',
  ],
  'trait.intellect_imagination': ['Intellect / Imagination', 'Интеллект / воображение'],
}
export function labelFor(key, locale) {
  return LABELS[key]?.[locale === 'ru' ? 1 : 0] || key
}
export function explanationFor(key, locale) {
  const ru = locale === 'ru'
  return (
    {
      'state.problem_intensity': ru
        ? 'Ваша оценка силы текущей трудности. Меньше баллов означает меньшую выраженность в этот момент.'
        : 'Your rating of the current difficulty. Fewer points mean less difficulty reported at that moment.',
      'state.resource': ru
        ? 'Сколько сил и внутренней опоры вы ощущали в момент ответа. Это не объективная оценка здоровья.'
        : 'How much energy and inner support you felt at the time. This is not an objective health score.',
      'state.tension': ru
        ? 'Внутреннее напряжение по вашей оценке в момент ответа.'
        : 'The inner tension you reported at the time of answering.',
      'state.fatigue': ru
        ? 'Усталость по вашей самооценке в момент ответа.'
        : 'Tiredness as you rated it at the time of answering.',
      'state.life_impact': ru
        ? 'Насколько текущая трудность мешала тому, что вы хотели делать.'
        : 'How much the current difficulty interfered with what you wanted to do.',
      'weekly.mood': ru ? 'Общая субъективная оценка эмоционального состояния за последние 7 дней.' : 'Your overall subjective emotional state across the past 7 days.',
      'weekly.tension': ru ? 'Самооценка тревоги и внутреннего напряжения за последние 7 дней.' : 'Self-reported anxiety and inner tension across the past 7 days.',
      'weekly.load': ru ? 'Насколько тяжёлой ощущалась общая психологическая нагрузка.' : 'How heavy your overall stress or mental load felt.',
      'weekly.recovery': ru ? 'Насколько восстановившимся вы чувствовали себя после сна или отдыха.' : 'How restored you felt after sleep or rest.',
      'weekly.energy': ru ? 'Сколько доступной энергии вы ощущали для повседневной жизни.' : 'How much usable energy you felt you had for daily life.',
      'weekly.clarity': ru ? 'Насколько ясным и собранным ощущалось мышление.' : 'How clear and focused your thinking felt.',
      'weekly.connection': ru ? 'Насколько вы ощущали связь и поддержку со стороны других людей.' : 'How supported and connected to other people you felt.',
      'weekly.functioning': ru ? 'Насколько хорошо вам удавалось делать нужные или желаемые дела.' : 'How well you were able to do the things you needed or wanted to do.',
      'trait.extraversion': ru
        ? 'Самоописание общительности и участия в контакте. Высокий или низкий балл сам по себе не лучше и не хуже.'
        : 'How you describe sociability and engagement. A higher or lower score is not inherently better.',
      'trait.agreeableness': ru
        ? 'Самоописание внимания к чувствам других людей.'
        : 'Self-description of attention to other people’s feelings.',
      'trait.conscientiousness': ru
        ? 'Самоописание организованности и привычек выполнения дел.'
        : 'Self-description of organization and habits around completing tasks.',
      'trait.neuroticism': ru
        ? 'Больше баллов означает больше эмоциональной реактивности в исходном ключе. Это не диагноз и не перевёрнутая шкала стабильности.'
        : 'More points mean more self-reported emotional reactivity in the original key. Not a diagnosis or an inverted stability scale.',
      'trait.intellect_imagination': ru
        ? 'Самоописание воображения и интереса к абстрактным идеям. Не измеряет IQ.'
        : 'Self-description of imagination and interest in abstract ideas. Does not measure IQ.',
    }[key] || ''
  )
}
